### ISSUE TITLE
forget to delete your password of the database 

### ISSUE THREAD

**Issue by donsmak** [haris-bit/simple-crud-app-backend#1]
hey just watched the tutorial in freecodecamp channel which iam very grateful  i just git cloned the repo to work on it to add some more features like asyncwrapper  and some error handlers as test ....and tested if i still could connect to database and yeah its still working  just wanted to let u know  so anyone with bad intentions wouldnt abuse it...

**Comment by haris-bit** [comment]
Thank you for letting me know. It was a practice database so no need to
worry about it.
